
package dmws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DMWsrv", targetNamespace = "http://dmws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DMWsrv {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://dmws/", className = "dmws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://dmws/", className = "dmws.LoginResponse")
    @Action(input = "http://dmws/DMWsrv/loginRequest", output = "http://dmws/DMWsrv/loginResponse")
    public boolean login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lookupRights", targetNamespace = "http://dmws/", className = "dmws.LookupRights")
    @ResponseWrapper(localName = "lookupRightsResponse", targetNamespace = "http://dmws/", className = "dmws.LookupRightsResponse")
    @Action(input = "http://dmws/DMWsrv/lookupRightsRequest", output = "http://dmws/DMWsrv/lookupRightsResponse")
    public String lookupRights(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
