
package dmws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DMWSService", targetNamespace = "http://dmws/", wsdlLocation = "http://157.159.15.73:9000/DMWsrv?wsdl")
public class DMWSService
    extends Service
{

    private final static URL DMWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DMWSSERVICE_EXCEPTION;
    private final static QName DMWSSERVICE_QNAME = new QName("http://dmws/", "DMWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://157.159.15.73:9000/DMWsrv?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DMWSSERVICE_WSDL_LOCATION = url;
        DMWSSERVICE_EXCEPTION = e;
    }

    public DMWSService() {
        super(__getWsdlLocation(), DMWSSERVICE_QNAME);
    }

    public DMWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DMWSSERVICE_QNAME, features);
    }

    public DMWSService(URL wsdlLocation) {
        super(wsdlLocation, DMWSSERVICE_QNAME);
    }

    public DMWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DMWSSERVICE_QNAME, features);
    }

    public DMWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DMWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DMWsrv
     */
    @WebEndpoint(name = "DMWSPort")
    public DMWsrv getDMWSPort() {
        return super.getPort(new QName("http://dmws/", "DMWSPort"), DMWsrv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DMWsrv
     */
    @WebEndpoint(name = "DMWSPort")
    public DMWsrv getDMWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dmws/", "DMWSPort"), DMWsrv.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DMWSSERVICE_EXCEPTION!= null) {
            throw DMWSSERVICE_EXCEPTION;
        }
        return DMWSSERVICE_WSDL_LOCATION;
    }

}
